catalogMode: prefer

registry: https://registry.npmmirror.com

# 用于控制是否严格检查对等依赖（peer dependencies）的版本一致性。
# 当设置为 true 时，pnpm 会强制安装指定版本的对等依赖；
# 设置为 false 时，会忽略版本不一致的警告
strictPeerDependencies: false
# 是否忽略向工作区根目录添加依赖时的警告提示
ignoreWorkspaceRootCheck: true
# 是否强制提升所有依赖
shamefullyHoist: true
# 在执行脚本时使用POSIX shell模拟器替代系统原生shell
shellEmulator: true

catalogs:
  dev:
    '@iconify-json/mdi': ^1.2.3
    '@lincy/unocss-base-config': ^2.4.2
    '@vitejs/plugin-vue': ^6.0.4
    '@vitejs/plugin-vue-jsx': ^5.1.4
    '@vue-macros/volar': ^3.1.2
    cross-env: ^10.1.0
    lint-staged: ^16.2.7
    mockjs: ^1.1.0
    postcss: ^8.5.6
    postcss-px-to-viewport-8-plugin: ^1.2.5
    sass-embedded: ^1.97.3
    tslib: ^2.8.1
    typescript: ^5.9.3
    unocss: ^66.6.0
    unplugin-auto-import: ^20.3.0
    unplugin-icons: ^23.0.1
    unplugin-vue-components: ^31.0.0
    url-search-params-polyfill: ^8.2.5
    vite: ^7.3.1
    vite-plugin-inspect: ^11.3.3
    vite-plugin-mock: ^3.0.2
    vite-plugin-progress: ^0.0.7
    vue-macros: ^3.1.2
    vue-tsc: ^3.2.4

  lint:
    '@lincy/eslint-config': ^6.4.0
    '@lincy/stylelint-config': ^2.2.1
    '@unocss/eslint-plugin': ^66.6.0
    eslint: ^9.39.2
    stylelint: ^16.26.1

  prod:
    '@lincy/utils': ^0.7.3
    '@unhead/vue': ^2.1.4
    '@vueuse/core': ^14.2.1
    axios: ^1.13.5
    default-passive-events: ^4.0.0
    lodash: ^4.17.23
    md5: ^2.3.0
    pinia: ^3.0.4
    qs: ^6.14.1
    store2: ^2.14.4
    unhead: ^2.1.4
    vant: ^4.9.22
    vue: ^3.5.28
    vue-cropper: ^1.1.4
    vue-router: ^4.6.4

  types:
    '@types/lodash': ^4.17.23
    '@types/node': ^24.10.12
    '@types/qs': ^6.14.0

onlyBuiltDependencies:
  - vue-demi

peerDependencyRules:
  ignoreMissing:
    - rollup
    - postcss
    - esbuild
    - prettier
