/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import { GlobalComponents } from 'vue'

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    EmptyComponents: typeof import('./components/empty-components.vue')['default']
    ImgList: typeof import('./components/img-list.vue')['default']
    JsxComponents: typeof import('./components/jsx-components.tsx')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ULoadmore: typeof import('./components/u-loadmore.vue')['default']
    VanButton: typeof import('vant/es')['Button']
    VanCell: typeof import('vant/es')['Cell']
    VanCellGroup: typeof import('vant/es')['CellGroup']
    VanDatePicker: typeof import('vant/es')['DatePicker']
    VanDialog: typeof import('vant/es')['Dialog']
    VanField: typeof import('vant/es')['Field']
    VanGrid: typeof import('vant/es')['Grid']
    VanGridItem: typeof import('vant/es')['GridItem']
    VanImage: typeof import('vant/es')['Image']
    VanImagePreview: typeof import('vant/es')['ImagePreview']
    VanList: typeof import('vant/es')['List']
    VanLoading: typeof import('vant/es')['Loading']
    VanNavBar: typeof import('vant/es')['NavBar']
    VanPopup: typeof import('vant/es')['Popup']
    VanPullRefresh: typeof import('vant/es')['PullRefresh']
    VanSkeleton: typeof import('vant/es')['Skeleton']
    VanTab: typeof import('vant/es')['Tab']
    VanTabbar: typeof import('vant/es')['Tabbar']
    VanTabbarItem: typeof import('vant/es')['TabbarItem']
    VanTabs: typeof import('vant/es')['Tabs']
  }
}

// For TSX support
declare global {
  const EmptyComponents: typeof import('./components/empty-components.vue')['default']
  const ImgList: typeof import('./components/img-list.vue')['default']
  const JsxComponents: typeof import('./components/jsx-components.tsx')['default']
  const RouterLink: typeof import('vue-router')['RouterLink']
  const RouterView: typeof import('vue-router')['RouterView']
  const ULoadmore: typeof import('./components/u-loadmore.vue')['default']
  const VanButton: typeof import('vant/es')['Button']
  const VanCell: typeof import('vant/es')['Cell']
  const VanCellGroup: typeof import('vant/es')['CellGroup']
  const VanDatePicker: typeof import('vant/es')['DatePicker']
  const VanDialog: typeof import('vant/es')['Dialog']
  const VanField: typeof import('vant/es')['Field']
  const VanGrid: typeof import('vant/es')['Grid']
  const VanGridItem: typeof import('vant/es')['GridItem']
  const VanImage: typeof import('vant/es')['Image']
  const VanImagePreview: typeof import('vant/es')['ImagePreview']
  const VanList: typeof import('vant/es')['List']
  const VanLoading: typeof import('vant/es')['Loading']
  const VanNavBar: typeof import('vant/es')['NavBar']
  const VanPopup: typeof import('vant/es')['Popup']
  const VanPullRefresh: typeof import('vant/es')['PullRefresh']
  const VanSkeleton: typeof import('vant/es')['Skeleton']
  const VanTab: typeof import('vant/es')['Tab']
  const VanTabbar: typeof import('vant/es')['Tabbar']
  const VanTabbarItem: typeof import('vant/es')['TabbarItem']
  const VanTabs: typeof import('vant/es')['Tabs']
}